# .github/workflows/deploy.yml
name: Deploy Family Allowance Tracker

on:
  push:
    branches: [ main, gh-pages ]
  pull_request:
    branches: [ main, gh-pages ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
        PUBLIC_URL: /family-allowance-tracker

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

---

# package.json
{
  "name": "family-allowance-tracker",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "lucide-react": "^0.263.1"
  },
  "devDependencies": {
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "@vitejs/plugin-react": "^4.0.3",
    "vite": "^4.4.5"
  }
}

---

# vite.config.js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  base: '/family-allowance-tracker/',
  build: {
    outDir: 'dist',
  },
})

---

# index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Family Allowance Tracker</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>

---

# src/main.jsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'

const repoOwner = 'natebarksdale'; // Replace with your GitHub username
const repoName = 'barksdale-family'; // Replace with your repository name

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App repoOwner={repoOwner} repoName={repoName} />
  </React.StrictMode>,
)

---

# src/App.jsx
// This will contain the updated React component with GitHub API integration
// (See next artifact)

---

# data/ledger.json
{
  "kids": [
    {
      "id": 1,
      "name": "Alex",
      "age": 5,
      "allowance": 25.50,
      "savings": {
        "cash": 15.00,
        "moneyMarket": 8.25,
        "sp500": 2.25,
        "tithe": 0.00
      },
      "tabletTokens": 12,
      "behaviorPoints": 45,
      "streaks": {
        "chores": 3,
        "bedtime": 7,
        "homework": 0
      }
    },
    {
      "id": 2,
      "name": "Jordan",
      "age": 7,
      "allowance": 42.75,
      "savings": {
        "cash": 20.00,
        "moneyMarket": 15.50,
        "sp500": 7.25,
        "tithe": 0.00
      },
      "tabletTokens": 8,
      "behaviorPoints": 38,
      "streaks": {
        "chores": 5,
        "bedtime": 2,
        "homework": 4
      }
    },
    {
      "id": 3,
      "name": "Riley",
      "age": 9,
      "allowance": 63.25,
      "savings": {
        "cash": 35.00,
        "moneyMarket": 20.00,
        "sp500": 8.25,
        "tithe": 0.00
      },
      "tabletTokens": 15,
      "behaviorPoints": 52,
      "streaks": {
        "chores": 8,
        "bedtime": 4,
        "homework": 6
      }
    }
  ],
  "transactions": [],
  "lastUpdated": "2025-05-27T00:00:00Z"
}

---

# README.md
# Family Allowance Tracker

A web application for tracking children's allowances, savings, behavior points, and more!

## Features

- **Parent Dashboard**: Manage allowances, points, and view transaction history
- **Kids View**: Kid-friendly interface for viewing balances and managing savings
- **Savings Categories**: Money Market, S&P 500, Cash, and Tithe
- **Behavior Tracking**: Points, tablet tokens, and streak counters
- **Persistent Data**: Uses GitHub repository for data storage

## Setup Instructions

1. **Fork this repository**
2. **Enable GitHub Pages**:
   - Go to Settings → Pages
   - Source: Deploy from a branch
   - Branch: gh-pages
3. **Create a Personal Access Token**:
   - Go to Settings → Developer settings → Personal access tokens → Tokens (classic)
   - Generate new token with `repo` scope
   - Add as repository secret named `GITHUB_TOKEN`

## Local Development

```bash
npm install
npm run dev
```

## Deployment

The app automatically deploys to GitHub Pages when you push to the main branch.

## Data Storage

Data is stored in `data/ledger.json` and automatically committed when changes are made through the parent dashboard.

## Usage

- **Parent View**: Use the parent dashboard to manage all aspects of the allowance system
- **Kids View**: Let your children access their personal dashboard to view balances and move money between savings categories
- **Data Backup**: Export/import functionality available in parent view

## Customization

Edit the initial data in `data/ledger.json` to match your family's setup.